### PR TITLE
Lazy fix for Google adding nonce to their script tags.

### PR DESCRIPTION
**Pull request by mikamikem**
Someone who actually knows how this works should really fix this properly, but this is a quick and dirty fix to just discard them and it seems to fix YakYak.

### CODE REVIEW

**Comment by zapotec83** [comment]
I confirm this fix works under Windows yakyak client

**Comment by plessbd** [comment]
I confirm this works on macOS 10.13.4 YakYak v1.5.0 client

**Comment by hastebrot** [comment]
I can also confirm. Works on macOS 10.12.6 with plain hangupsjs.

**Comment by danbob** [comment]
Wouldn't it be better to just remove all script tags?
```javascript
html = html.replace /<\/?script.*?>/gm, ''
```
The string is eval'd immediately after this bit, so if there are any script tags left it's going to break. If one gets added later that shouldn't be removed like this it will have to be handled separately anyway.

**Comment by sosguthorpe** [comment]
@danbob - My original thoughts were just that. But after examining the page this actions on it doesn't act on certain script tags on purpose. I even tested with a similar regex in place (basically I had [^>] instead of the .* you have as the dot would remove all the content between the last closing bracket greedily), and the library didn't work.
So I came to the conclusion the intention was to not remove all script tags.

**Comment by danbob** [comment]
Well it does work to fix yakyak (per yakyak/yakyak#919) but if this library is used for more than just that project then perhaps it needs to be more discriminating.

**Pull request closed without merging**
